[tool.poetry]
# Change this section to be project specific
name = "terravision"
version = "0.0.1"
description = "Terraform Diagram Visualizer"
authors = []
readme = 'README.md'
exclude = []


[tool.poetry.dependencies]
click = "8.1.3"
GitPython = "3.1.31"
graphviz = "0.20.1"
requests = "2.28.2"
setuptools = "65.6.3"
tqdm = "4.65.0"
python-hcl2 = "4.3.0"
pyinstaller = "5.8.0"
python = ">=3.9.16,<3.11"
PyYAML = "6.0"
